language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t abhipatel7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhipatel7/docker-react npm run test -- --coverage