language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t abhipatel7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhipatel7/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-150582750569"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key